Tests: Bash Output Improvement
Print line after failed command to increase readability.

diff --git a/tests/run_parallel_tests b/tests/run_parallel_tests
--- a/tests/run_parallel_tests
+++ b/tests/run_parallel_tests
@@ -8,12 +8,10 @@ mkdir $dir/h5
 cd $dir
 OK=0
 
-function testSerial()
+function testLast()
 {
-    if [ -e "$1" ]; then
-        echo -e "\n$2\n"
-        $1
-        OK=$(( OK + $? ))
+    if [ $1 -ne 0 ]; then
+        echo "An error occured in $2..."
     fi
 }
 function testMPI()
@@ -21,7 +19,9 @@ function testMPI()
     if [ -e "$1" ]; then
         echo -e "\n$3\n"
         mpirun -n $2 $1
-        OK=$(( OK + $? ))
+        last=$?
+        testLast $last $1
+        OK=$(( OK + $last ))
     fi
 }
 
